# Generated by Django 4.0.5 on 2022-06-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
        ),
    ]
