# Generated by Django 4.0.5 on 2022-06-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
        ('tracklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracklist',
            name='tracks',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.track'),
        ),
    ]
