# Generated by Django 4.0.5 on 2022-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_remove_user_profile_image_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
