# Generated by Django 4.0.5 on 2022-06-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('album_art', models.CharField(default=None, max_length=100)),
                ('artist', models.ManyToManyField(related_name='albums', to='artists.artist')),
                ('genres', models.ManyToManyField(related_name='albums_genre', to='genres.genre')),
            ],
        ),
    ]
