# Generated by Django 4.0.5 on 2022-06-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
        ('tracks', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='albums_artist', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='albums_genre', to='genres.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='albums_tracks', to='tracks.track'),
        ),
    ]
