# Generated by Django 4.0.5 on 2022-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('genres', '0001_initial'),
        ('tracks', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(default='Artist', related_name='albums_artist', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(default='Genre', related_name='albums_genre', to='genres.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(default='Track', related_name='albums_tracks', to='tracks.track'),
        ),
    ]
