# Generated by Django 4.0.5 on 2022-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0002_initial'),
        ('tracks', '0001_initial'),
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(default='Artist', related_name='albums_artist', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(default='Genre', related_name='albums_genre', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(default='Track', related_name='albums_tracks', to='tracks.track'),
        ),
    ]
