# Generated by Django 4.0.5 on 2022-06-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_trackurl'),
        ('userPlaylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='tracks',
            field=models.ManyToManyField(to='tracks.track'),
        ),
    ]
