# Generated by Django 4.0.5 on 2022-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('info', models.TextField()),
                ('album', models.ManyToManyField(related_name='albums_artist', to='albums.album')),
            ],
        ),
    ]
