# Generated by Django 4.0.5 on 2022-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='track',
            field=models.ManyToManyField(blank=True, related_name='artist_track', to='tracks.track'),
        ),
    ]
