# Generated by Django 4.0.5 on 2022-06-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_album_art_alter_album_artist_and_more'),
        ('tracks', '0001_initial'),
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='albums_artist', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track',
            field=models.ManyToManyField(blank=True, related_name='artist_track', to='tracks.track'),
        ),
    ]
